[build]
builder = "nixpacks"
buildCommand = "python -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt"

[deploy]
startCommand = ". .venv/bin/activate && python db_init.py && gunicorn -b 0.0.0.0:$PORT run:app"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 20