[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python db_init.py && gunicorn -b 0.0.0.0:${PORT:-8080} run:app --log-level debug --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 20