[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt gunicorn"

[deploy]
startCommand = "python db_init.py && export PORT=${PORT:-8080} && gunicorn -b 0.0.0.0:$PORT run:app --log-level debug --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 20