[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python db_init.py && cd .. && FLASK_ENV=development gunicorn -b 0.0.0.0:$PORT wsgi:app --log-level debug"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 20